# Generated by Django 3.0.8 on 2021-10-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_code', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('destination', models.CharField(max_length=30)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('no_of_seat', models.DecimalField(decimal_places=0, max_digits=2)),
                ('remaining_seat', models.DecimalField(decimal_places=0, max_digits=2)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.BooleanField(default=1)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusCategoryModel')),
            ],
        ),
    ]
